@startuml

skinparam linetype ortho
skinparam nodesep 100
skinparam ranksep 80

!includesub connection.puml!CONNECTION
!includesub benchmark_runner.puml!BENCHMARK_RUNNER
!includesub benchmark_inspector.puml!BENCHMARK_INSPECTOR

@enduml