@startuml

skinparam linetype ortho
skinparam nodesep 120
skinparam ranksep 80

!startsub CONNECTION

abstract class Connection {
    - last_message : Message
    - socket : ZMQ_Socket
    + __init__(config : ConnectionConfig)
    + start_connection()
    + send_message(message : Message)
    + get_last_message() : Message
    + close_connection()
    + get_status()
    'Error handling made by the functions
    'Possible errors:
    ' - Cannot create connection (port already bound, other errors)
    ' - Wrong message sent
    ' - Unidirectional Sockets will provide a dummy last_message() or send message()
}

class ClientConnection {

}

class ServerConnection {

}

Connection <|-- ServerConnection
Connection <|-- ClientConnection
ServerConnection -[hidden]r-> ClientConnection
!endsub

class Message {
    - title : str
    - content : str
    + __init__(title : str, content : str)
    + get_title() : str
    + get_content() : str
}

interface ConnectionConfig {
    + get_address() : str
}

class TCPConnectionConfig {
    - address : str
    __init__(host : str, port : str)
}

class InProcessConnectionConfig {
    To be added later...
}

Connection "*" -l-- "1" ConnectionConfig : <<for setup>>
Connection ..r.> Message : <<send/receives>>
ConnectionConfig <|-- InProcessConnectionConfig
ConnectionConfig <|-- TCPConnectionConfig
note top of Connection: Based on ZeroMQ library
note bottom of TCPConnectionConfig : this is the default choice: tcp:\\\\*:9361

@enduml