@startuml
skinparam linetype ortho
skinparam nodesep 100
skinparam ranksep 100

!startsub MAP
class Graph {
    - graph : Graph (from python_igraph)
    + __init__(nodes_number : int, edge_list : Edge[])
    + get_nodes : (Node[])
    + get_edges : (Edge[])
    + get_node(position : Position) : Node
}

class Node {
    ' - position : Position
    ' - adjacent_nodes : Tuple(Node)
    ' - starting_edges : Tuple(Edge)
    ' - ending_edges : Tuple(Edge)
    + get_position() : Position
    + get_index() : Index
    + get_adjacent_nodes() : tuple(Node[0..*])
    + get_starting_edges() : tuple(Edge[0..*])
    '+ get_ending_edges() : tuple(Edge[0..*])
}

class Edge {
    '- start : Node
    '- end : Node
    - weight: int
    + __init__(self, start : Node, end : Node, weight : int)
    + get_nodes() : (Node, Node)
    + get_start_node() : Node
    + get_end_node() : Node
    + get_weight() : Node
    + get_information() : (Node, Node, int)
}

class Position {
    - x : int
    - y : int

    + __init__(self, x : int, y : int)
    + get_coordinates() : (int, int)
    + __str__() : str
}

Graph --* "*" Node
Graph --* "*" Edge
Edge --o "2   " Node : - start, end
Node --> Position : - position

!endsub

@enduml